name: release
on: workflow_dispatch
jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev pkg-config

      - name: build release
        run: cargo build --release

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ding-${{ matrix.os }}
          path: target/release/ding
